"""
Django settings for helloworld project.

Generated by 'django-admin startproject' using Django 4.2.24.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*_cve2-zmc(gm916!sp)xili6-*&9=mo!&#dy5i9b+(ff=l%3e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Temporarily enable for debugging

# Add your EC2 instance's public IP or domain name here
ALLOWED_HOSTS = ['*']

# CSRF and proxy configuration for load balancer
CSRF_TRUSTED_ORIGINS = [
    'https://*.amazonaws.com',
    'https://*.cloudfront.net',
    'https://d38z5mn4ejjzoo.cloudfront.net',
    'https://*.elb.amazonaws.com',
    'http://*.elb.amazonaws.com',
    'http://localhost',
    'http://127.0.0.1',
    'http://*',  # Permite cualquier IP HTTP para desarrollo
    'https://*', # Permite cualquier IP HTTPS para desarrollo
]

# CSRF configuration for load balancer and CloudFront
CSRF_COOKIE_SECURE = True  # False porque ALB termina SSL
CSRF_COOKIE_HTTPONLY = True  # Permite JavaScript acceso
CSRF_USE_SESSIONS = False  # Usar cookies, no sesiones
CSRF_COOKIE_SAMESITE = None  # None para cross-site requests
CSRF_COOKIE_DOMAIN = os.environ.get('CLOUDFRONT_DOMAIN') or None  # No restringir dominio

# Configuración específica para proxies
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'
CSRF_COOKIE_MASKED = True

# Trust proxy headers from ALB and CloudFront
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Additional proxy configuration
SECURE_SSL_REDIRECT = False  # ALB maneja SSL
SECURE_REDIRECT_EXEMPT = []  # No redirigir desde Django

# Configuración para CloudFront y proxies
ALLOWED_HOSTS = ['*']

# Configuración adicional para CSRF con proxies
if 'HTTP_X_FORWARDED_PROTO' in os.environ:
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False

# Additional CSRF configuration for proxy setup
CSRF_TRUSTED_ORIGINS.extend([
    'http://goss-3028-django-acg-1-1517049356.us-east-1.elb.amazonaws.com',
    'https://goss-3028-django-acg-1-1517049356.us-east-1.elb.amazonaws.com',
    'https://d38z5mn4ejjzoo.cloudfront.net',  # CloudFront domain específico
    'http://d38z5mn4ejjzoo.cloudfront.net',   # CloudFront HTTP (si aplica)
])

# Session configuration for load balancer
SESSION_COOKIE_SECURE = False  # ALB termina SSL
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = None  # None para cross-site
SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_PATH = '/'
SESSION_COOKIE_AGE = 1209600  # 2 semanas
SESSION_SAVE_EVERY_REQUEST = True  # Guardar sesión en cada request

# Temporal: Deshabilitar CSRF para desarrollo si es necesario
# Descomenta la siguiente línea si sigues teniendo problemas CSRF
# CSRF_COOKIE_NAME = None


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    'helloworld',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'helloworld.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'helloworld.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASS'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# AWS S3 settings for static and media files
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_BUCKET_STATIC')

# Use CloudFront domain instead of direct S3
CLOUDFRONT_DOMAIN = os.environ.get('CLOUDFRONT_DOMAIN')
if CLOUDFRONT_DOMAIN:
    AWS_S3_CUSTOM_DOMAIN = CLOUDFRONT_DOMAIN
else:
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'

AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}
AWS_LOCATION = 'static'

STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/'

MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
